### ISSUE TITLE
Spring Boot parent

### ISSUE THREAD

**Issue by berniegp** [spring-guides/gs-multi-module#9]
Is there any reason to prefer having `spring-boot-starter-parent` as the parent of the "child" modules (e.g. `gs-multi-module-library`) instead of `gs-multi-module`? It seems that it would be easier to have `gs-multi-module` inherit from `spring-boot-starter-parent` and the other sub-modules inherit from `gs-multi-module`. I have used this setup myself and it works properly.

**Comment by dsyer** [comment]
I don’t think there’s any strong argument either way in general. In this specific case there is no advantage in adding an extra parent because the two projects don’t need to share any customizations that aren’t already in the starter parent. There might even be an advantage in leaving it as it is, if the two modules ever need to be split up into separate source control repos.

**Comment by berniegp** [comment]
Thanks for taking the time to answer. This makes sense.

In my case, I wanted to add some common dependency management entries in the parent POM.
